### ISSUE TITLE
Android run crash

### ISSUE THREAD

**Issue by whitelok** [RossMeikleham/PlutoBoy#34]
03-10 23:02:22.277 11390-11390/com.plutoboy.plutoboy E/AndroidRuntime: FATAL EXCEPTION: main
                                                                       Process: com.plutoboy.plutoboy, PID: 11390
                                                                       java.lang.UnsatisfiedLinkError: Native method not found: org.libsdl.app.SDLActivity.onNativeSurfaceChanged:()V
                                                                           at org.libsdl.app.SDLActivity.onNativeSurfaceChanged(Native Method)
                                                                           at org.libsdl.app.SDLSurface.surfaceChanged(SDLActivity.java:1131)
                                                                           at android.view.SurfaceView.updateWindow(SurfaceView.java:675)
                                                                           at android.view.SurfaceView.access$000(SurfaceView.java:90)
                                                                           at android.view.SurfaceView$3.onPreDraw(SurfaceView.java:195)
                                                                           at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:847)
                                                                           at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2190)
                                                                           at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1190)
                                                                           at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6258)
                                                                           at android.view.Choreographer$CallbackRecord.run(Choreographer.java:788)
                                                                           at android.view.Choreographer.doCallbacks(Choreographer.java:591)
                                                                           at android.view.Choreographer.doFrame(Choreographer.java:560)
                                                                           at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:774)
                                                                           at android.os.Handler.handleCallback(Handler.java:808)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:103)
                                                                           at android.os.Looper.loop(Looper.java:193)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5344)
                                                                           at java.lang.reflect.Method.invokeNative(Native Method)
                                                                           at java.lang.reflect.Method.invoke(Method.java:515)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:825)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:641)
                                                                           at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
                                                                           at dalvik.system.NativeStart.main(Native Method)

**Comment by RossMeikleham** [comment]
Hi, would you be able to supply which ROM you were running, as well as the device and Android version your device was on? Also did this occur when booting a ROM or during gameplay? If during gameplay would you be able to tell me which point?

**Comment by whitelok** [comment]
I think this error is caused by no implement JNI method onNativeSurfaceChanged instead of the ROM.
If you have any idea about this. Welcome discuss with me.
